### ISSUE TITLE
App launch from launchpad does not show the app if app is already open.

### ISSUE THREAD

**Issue by kingdomcreation** [720kb/ndm#107]
* OS: OS X Sierra
* OS version: 10.12.1
* ndm version: 0.0.5-beta
* node version: v7.3.0
* npm version: 3.10.10
* npm permissions (fixed, not-fixed)(see https://docs.npmjs.com/getting-started/fixing-npm-permissions):
* node installed via (brew, n, nvm, pkg, other ...): nvm
* How to replicate the bug/issue, if you know it: open ndm, click on ndm icon in Launchpad

![screenshot 2017-01-11 13 59 17](https://cloud.githubusercontent.com/assets/3534030/21862218/3e7bd27a-d806-11e6-8085-8f90840000ca.png)

**Comment by 45kb** [comment]
@kingdomcreation hi, thanks for the report, you're right, i just noticed that this should not happen. 

Btw download a newer app version as soon as you can ;)
We'll be fixing this problem, thanks

**Comment by 45kb** [comment]
Seems fixed now, will be released within the next version! https://github.com/720kb/ndm/commit/246c92bdff37caa80d0ae457f073fe974ffac0d9

**Comment by 45kb** [comment]
reminder: Ok problem seems to be this `process.env.PATH = require('shell-path').sync();` called at top of index.js main electron boot file.

**Comment by 45kb** [comment]
@kingdomcreation seems everythings ok with the new version (v0.1.3) get it if you want https://github.com/720kb/ndm/releases/download/v0.1.3/ndm-0.1.3.dmg 

Let know if still some problem but it's working great here 👍
