### ISSUE TITLE
npm global timing problems

### ISSUE THREAD

**Issue by 45kb** [720kb/ndm#119]
OS: Mac
How to replicate problem: when app starts start clicking compulsively on "global" project (even if you don't see it because app is loading) until it gets clicked (after app is loaded).

Doesn't happen if you wait 1 second after app is ready loaded.

I also get this error permanently when i build the app not on the local running app.

![schermata 2017-01-16 alle 09 21 55](https://cloud.githubusercontent.com/assets/7761650/21975539/8649ef5e-dbcd-11e6-8ff2-9ff121012b87.png)

**Comment by 45kb** [comment]
seems to fix https://github.com/720kb/ndm/commit/efb3df05cece5e0a59e674e9140c378f451b23ab but it's not the correct way to fix it ⛔️ 

 cc @wouldgo

**Comment by 45kb** [comment]
#129  seems to fix this totally @wouldgo then give it a 👀  when you can.

**Comment by 45kb** [comment]
unable to reproduce these errors, tried both on mac, linux everything seems fine. closing atm. https://github.com/720kb/ndm/pull/129

**Comment by wouldgo** [comment]
@45kb checked. Is good as it is now
