### ISSUE TITLE
Auto-updater

### ISSUE THREAD

**Issue by 45kb** [720kb/ndm#12]
As the Autoupdater it's ready and working, remove the temporary check for updates from this [file](https://github.com/720kb/ndm/blob/master/lib/js/index.js) and this [file](https://github.com/720kb/ndm/blob/master/lib/index.pug)

For better investigatioin, see this [commit](https://github.com/720kb/ndm/commit/6517cb4dc9752d600ed9eef0e233267212ce23b6)

**Comment by kathiedart** [comment]
Does the deb happen to use an apt repository? I suggest that would be a good idea.

**Comment by 45kb** [comment]
@kathiedart hey, that could be great really, can you help on this? (while we are focused on other problems to solve)

**Comment by kathiedart** [comment]
Sure, I'll investigate Launchpad

**Comment by 45kb** [comment]
@kathiedart thanks! 👍

**Comment by 45kb** [comment]
@wouldgo let's consider that @bil-elmoussaoui said he can test a lot of things on linux. 
Maybe he can help us to make some deeper test with the pkg auto updater ;)

**Comment by 45kb** [comment]
@kathiedart do you got any chance to look at launchpad, then? :)

**Comment by bil-elmoussaoui** [comment]
Yeah whatever you guys want :) I can also package ndm on launchpad for Ubuntu/Debian ;)

**Comment by wouldgo** [comment]
in [here](https://github.com/720kb/ndm/blob/auto-update/.travis.yml#L27) i started to use packagcloud to automatically manage debian and redhat packages automatically.

It's matter of finishing the process scenario about updating macos and windows application.

**Comment by 45kb** [comment]
@bil-elmoussaoui now that you already manage the Arch Linux if you can package the deb tho we'll be glad about it, let me know if you need any info/help. Look what @wouldgo said we are packaging the next release to get automatic updates maybe you can give it some tries i don't know :)
