### ISSUE TITLE
Minimize and Close actions displayed in the Help menu

### ISSUE THREAD

**Issue by strycore** [720kb/ndm#144]
## Issue Report

The Help menu features duplicated actions from the Window menu: Minimize and Close. Under "Follow on Twitter".
I would also suggest getting rid of the Window menu entirely as the actions provided are usually handled by the window manager and desktop app usually don't offer these actions from the main menu.

#### REQUIRED 
OS / OS version:  Ubuntu 16.10

ndm version:  0.1.4
 
node version: 7.4.0

npm version: 4.1.2

node installed via (brew, n, nvm, pkg, other ...):  nvm

#### IMPORTANT

- npm permissions fixed or not-fixed? (see https://docs.npmjs.com/getting-started/fixing-npm-permissions):  non relevant as I'm using nvm

- If you are using npm > v4.1.1 then run `npm doctor` and paste the output here:

#### APPRECIATED
_open the devtools console: OS Menu -> View -> Developer -> Open DevTools_

Now make a screenshot of your devtools console or paste the devtools console full-log in here:
npm ping                            ok
npm -v                              v4.1.2
node -v                             v7.4.0
npm config get registry             https://registry.npmjs.org/
which git                           /usr/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Checksum cached files               notOk                        You have some broken packages in your cache.

#### THE PROBLEM
I see Minimize and Close on the Help menu, also I don't need the Window menu as the actions are already provided by the window manager.

#### REPRODUCE THE PROBLEM
Click on the Help menu

**Comment by 45kb** [comment]
@strycore Hey, thanks for reporting this, isn't window menu field a standard that has something to do with accessibility? I don't know actually, on Mac i am pretty sure it's part of the accessibility...

As for the Help menu, yes must be removed cause they are in the wrong place :D

**Comment by strycore** [comment]
@45kb accessibility features should also be handled at the operating system level. As far as I remember, I can't think of any desktop software that includes those actions as part of the application's menu.
On Gnome, for example, there is a standard menu available when right-clicking on the title bar (or also available when the windows action button is enabled), this menu features minimize and close but also maximize, move, resize, etc. All those action are mapped to standardized keyboard shortcuts (which are configured at the OS level, not the application).

**Comment by 45kb** [comment]
@strycore great! thanks for the clarification :)

**Comment by 45kb** [comment]
@strycore will be fixed downloading the next upcoming release 👍 

thanks for your time.

**Comment by strycore** [comment]
Cool to see that fixed! 

Btw, you might want to gather opinions from Windows and Mac users. The stuff I posted above wasn't really Linux specific.

Anyway, as far as I'm concerned, I only use Linux so I'm happy :D 

(unrelated to this issue, I spoke about NDM on our last podcast! https://youtu.be/mzKX1rrfY5I?t=1467 )

**Comment by 45kb** [comment]
@strycore glad that you enjoying it, there are a lot of things that still must be improved and done :)

Thanks for talking about it on your podcast, that's COOL! 

If you find any bad behavior or malfunction, or just you have some idea/feature let know, you're welcome anytime here 👍

**Comment by strycore** [comment]
I was thinking about something earlier today, it would be rather cool if ndm could also handle bower :)

**Comment by 45kb** [comment]
@strycore i think, to achieve that it would be better to fork ndm and make bdm "bower desktop manager" :P :P

**Comment by strycore** [comment]
yes, it would probably be better as its own tool ^^

**Comment by 45kb** [comment]
@strycore yeah ;P
Appreciated don't worry.

Also, personally, i don't know if bower is still widely used, today you can use npm for all i guess... 🤔

**Comment by strycore** [comment]
It's used a lot among developers who use Polymer, it's the "official" way of installing components.

**Comment by 45kb** [comment]
@strycore oh didn't know that :)
