### ISSUE TITLE
Possibility to hide the OS menu

### ISSUE THREAD

**Issue by bil-elmoussaoui** [720kb/ndm#155]
#### REQUIRED 
OS / OS version:  Archlinux 

ndm version:  latest one 1.0.0
 
node version: v7.5.0

npm version: 4.1.2

node installed via (brew, n, nvm, pkg, other ...): 

#### OPTIONAL 

$ which node: `/usr/bin/node`

$ which npm: `/usr/bin/npm`

#### IMPORTANT

- npm permissions fixed or not-fixed? (see https://docs.npmjs.com/getting-started/fixing-npm-permissions): fixed

- If you are using npm > v4.1.1 then run `npm doctor` and paste the output here:

#### APPRECIATED
_open the devtools console: OS Menu -> View -> Developer -> Open DevTools_

Now make a screenshot of your devtools console or paste the devtools console full-log in here:

#### THE PROBLEM
What's the problem you facing,  in few lines:
I would like to request the possibility to hide the menu bar. As it's does not look that beautiful under any linux distro out there.
![screenshot from 2017-02-03 23-14-50](https://cloud.githubusercontent.com/assets/7660997/22610619/96433b66-ea66-11e6-9083-540e280f3e16.png)

#### REPRODUCE THE PROBLEM
How to reproduce the problem in few lines:

**Comment by 45kb** [comment]
@bil-elmoussaoui thanks for the advice.
Personally i don't know if it's a good practice to hide it, there are a bunch of features inside the menu (check for updates just for example...) i don't know if electron allows the toggling on it, i mean it is a native behavior i would no touch it but if you or anybody here have some idea on how to make it feel better let know guys!

**Comment by bil-elmoussaoui** [comment]
Well, Electron added the possibility to hide/show the menu! You can still add a shortcut to show it (for example ALT). The same as in Atom :)

**Comment by 45kb** [comment]
mmmmmm i don't like that much the idea to hide the menu, i mean, as it's really horrible it should start hidden by default then you could toggle it with shortcut, but that way is not so intuitive nope?!

**Comment by bil-elmoussaoui** [comment]
Nop it's not hidden by default on Atom
![screenshot from 2017-02-04 10-28-29](https://cloud.githubusercontent.com/assets/7660997/22617396/b1f38600-eac4-11e6-82f6-dde1eedf280e.png)
Once you click on Toggle menu bar; the menu becomes hidden and you can show it again by clicking on ALT.  
If it's possible to get a better design idea that does not involve the menu bar that would be perfect, but for now i think this should do it :)

**Comment by 45kb** [comment]
@bil-elmoussaoui thanks, ok i'll think of a solution for this, maybe just changing header color would look better, but i'll make some tries for this don't worry 👍

**Comment by bil-elmoussaoui** [comment]
Thanks! if you need me to test anything on Linux just let me know ;)

**Comment by 45kb** [comment]
[reminder] https://github.com/electron/electron/pull/817

**Comment by 45kb** [comment]
@bil-elmoussaoui should work and will be in the next release. Could you be so gentle to try it?

It's just to clone the repo and run:

`npm i && npm run linux`

👍

**Comment by bil-elmoussaoui** [comment]
Works like a charm :D 
![screenshot from 2017-02-07 21-16-45](https://cloud.githubusercontent.com/assets/7660997/22709643/d10459d0-ed7a-11e6-9d84-2f3d0c98a22e.png)
![screenshot from 2017-02-07 21-17-06](https://cloud.githubusercontent.com/assets/7660997/22709644/d10f26c6-ed7a-11e6-92fc-9665ac280fde.png)
Thank you!

**Comment by 45kb** [comment]
thanks @bil-elmoussaoui you're welcome, if you have some more ideas or needs for it, just let know then 👍

**Comment by bil-elmoussaoui** [comment]
Yeah, i have already an issue that i will report just now :) thanks for your work!
