### ISSUE TITLE
Description of packages might contain html tags

### ISSUE THREAD

**Issue by bil-elmoussaoui** [720kb/ndm#179]
#### REQUIRED 
OS / OS version:  Linux

ndm version:  1.1.0
 
node version: 6.9.5

npm version: 4.3.0

node installed via (brew, n, nvm, pkg, other ...):  package manager

#### OPTIONAL 

$ which node: /usr/bin/node

$ which npm: /usr/bin/npm
 
#### IMPORTANT

- npm permissions fixed or not-fixed? (see https://docs.npmjs.com/getting-started/fixing-npm-permissions):

- If you are using npm > v4.1.1 then run `npm doctor` and paste the output here:

#### APPRECIATED
_open the devtools console: OS Menu -> View -> Developer -> Open DevTools_

Now make a screenshot of your devtools console or paste the devtools console full-log in here:

#### THE PROBLEM
What's the problem you facing,  in few lines:
Some packages might contain html tags in their description  as you can see in the screenshot below, 
![screenshot from 2017-02-26 10-43-38](https://cloud.githubusercontent.com/assets/7660997/23338651/df7e7b2c-fc10-11e6-96d1-bb79e849864d.png)
I suggest, removing all html tags except a tags.  
Yarn package has the issue, maybe others too...

#### REPRODUCE THE PROBLEM
How to reproduce the problem in few lines:

Just install yarn and you will get this "bug"

**Comment by 45kb** [comment]
@bil-elmoussaoui Hey, thanks, this is indeed strange that someone is using html inside the description  field, that's not really a standard behavior as package.json should not include html tags .... afaik.

We will strip html tags off at all, consider that removing them in the Yarn package description (for example) will result in empty description.... their description: `<p align="center"> <a href="https://yarnpkg.com/"> <img alt="Yarn" src="https://github.com/yarnpkg/assets/blob/master/yarn-kitten-full.png?raw=true" width="546"> </a> </p>` :/

**Comment by bil-elmoussaoui** [comment]
Well, in that case, just remove html tags at all, it's better to have nothing then having something ugly ,)
