### ISSUE TITLE
Sort projects aphabetically

### ISSUE THREAD

**Issue by jaredreich** [720kb/ndm#196]
Looks like projects get sorted as they're added (making them hard to find later). Perhaps they should be sorted alphabetically.

**Comment by 45kb** [comment]
@jaredreich Hi, personally agree.
Even if the best option would be to be able to sort them just by dragging them up and down and save the order imho.

My only doubt is: wouldn't be better to sort them by the date they are added into the view? 

Would be nice if even others gives their point of view on this 👍

**Comment by jaredreich** [comment]
@45kb Sorting by date/time added is not the right way to do it, users will get frustrated that once their project is added it's stuck in that order and they'll have to remove all projects and re-add them in the specific way, then repeat the whole process every time they add a new project.

I would say the best option is dragging and saving, second best option is sort alphabetically.

Also, after my strong opinion, I would like to say thank you for making this great software in the first place. Well done!

**Comment by 45kb** [comment]
@jaredreich thanks, you're welcome and i definitively agree, alpha ASC order by default + order drag-n-save would be quite definitive... @wouldgo what you think?
