### ISSUE TITLE
[Tab Views] Install error "Path must be a string"

### ISSUE THREAD

**Issue by 45kb** [720kb/ndm#200]
SOmething wrong is happening when you try to install a new package.
![schermata 2017-05-07 alle 09 14 45](https://cloud.githubusercontent.com/assets/7761650/25778688/cce3a2ea-3305-11e7-9515-c57ddccf44fe.png)

**Comment by wouldgo** [comment]
:rocket:

**Comment by wouldgo** [comment]
@45kb try it but I'm almost sure that now works :dancing_men:

**Comment by 45kb** [comment]
yesss! @wouldgo
