### ISSUE TITLE
[Tab Views] Doesn't install the specific package version

### ISSUE THREAD

**Issue by 45kb** [720kb/ndm#209]
Specifying package version doesn't work, you get latest version of the package anyway.
![schermata 2017-05-07 alle 18 01 38](https://cloud.githubusercontent.com/assets/7761650/25782655/6796b478-334f-11e7-9e49-818f83faa041.png)

**Comment by 45kb** [comment]
made a dup of this: https://github.com/720kb/ndm/issues/202

**Comment by wouldgo** [comment]
closed with e6f7bc01311951e6c98213001e5204f71aad9191
