### ISSUE TITLE
[Tab Views] Installing global package then "command not found"

### ISSUE THREAD

**Issue by 45kb** [720kb/ndm#225]
**REPRODUCE IT:**
 - Install `yogurl` globally with ndm

 - Once is installed open the terminal and run: 
    $ npm list --depth=0
    --> _yogurl is present and installed_

 - Run `yogurl ` in terminal
    _ERR command not found_

**EXPECTED BEHAVIOR**
This doesn't happen if you install yogurl by the terminal `npm i -g yogurl`

  - Run `yogurl ` in terminal after is installed globally with no errors (means yogurl command is installed)

**INFOS**
- MacOS Sierra latest
- node 6.10.3
- npm 4.6.1

npm doctor:

```Check                               Value                        Recommendation
npm ping                            OK
npm -v                              v4.6.1
node -v                             v6.10.3
npm config get registry             https://registry.npmjs.org/
which git                           /usr/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Checksum cached files               ok```

**Comment by 45kb** [comment]
@wouldgo dunno what is happening sincerely 🎱

**Comment by wouldgo** [comment]
done :rocket:

**Comment by 45kb** [comment]
😮  🌠

**Comment by 45kb** [comment]
such @wouldgo much 💣  

tried it and it works like a charm.
