### ISSUE TITLE
Change the default font on Windows to Roboto

### ISSUE THREAD

**Issue by NickolasGame** [720kb/ndm#234]

**Comment by 45kb** [comment]
@NickolasGame why does sorry?

**Comment by NickolasGame** [comment]
Because the current font-family on windows is terrible. Maybe it be better to change the font to Segoe UI because Roboto is not system font.

**Comment by 45kb** [comment]
@NickolasGame sorry i don't get you sincerely, the default font is SEGOE UI  in the css https://github.com/720kb/ndm/blob/master/lib/scss/win/win.scss#L3 and you are asking to switch to Roboto in the issue title ... can you please clarify and send a screenshot?

thank you.

**Comment by NickolasGame** [comment]
Sorry

**Comment by 45kb** [comment]
np @NickolasGame
