### ISSUE TITLE
etc/ folder on empty projects

### ISSUE THREAD

**Issue by 45kb** [720kb/ndm#3]
When you add an empty project folder and install a package, it creates a package.json (correct) and an `etc/` folder (wrong) inside the project folder.

Actually... this seems to be npm behavior, so it's possible that we can't do anything for that.

Just worths to check if it's fixable or for some work around.

**Comment by wouldgo** [comment]
Closed with PR #118 due to the change how npm install command is managed.

**Comment by deathart** [comment]
Possible to solve this problem? Because it is still relevant
