### ISSUE TITLE
Add linux release

### ISSUE THREAD

**Issue by madnight** [720kb/ndm#45]
Could you provide a .deb package for distributors?

**Comment by 45kb** [comment]
@madnight 
If you want to build a different release just edit this field https://github.com/720kb/ndm/blob/master/package.json#L31

and run ```npm run build```

At the moment is not reccomended to use it outside of OSX

Ubuntu and Windows will be released asap.

**Comment by mightyiam** [comment]
http://flatpak.org/ perhaps?

**Comment by 45kb** [comment]
@mightyiam Hi, we use default [electron-builder](https://github.com/electron-userland/electron-builder)

**Comment by mightyiam** [comment]
Cool. I don't know which of all of these formats I would use. It seems that AppImage and snap are the candidates, then.

**Comment by 45kb** [comment]
@mightyiam worths to try it 👍

**Comment by 45kb** [comment]
https://github.com/720kb/ndm/issues/53
