### ISSUE TITLE
Win release

### ISSUE THREAD

**Issue by 45kb** [720kb/ndm#52]
later
meantime: https://github.com/720kb/ndm#build

**Comment by 45kb** [comment]
We have to focus on some features and bugs that happen, before to be able to say it works, so multiple OSs will be confusing. 
The npm API is quite (i'd say totally) cross-platform, and the app IS the npm API itself.

Then steps will be simple:

- adapt css to win
- adapt gulp tasks for build and release (i.e: switching css files before to build , or the os menu template for example , etc ..)

In the meantime a proposal of a CSS UI for Windows would be much appreciated!

The layout will not change (same dispositions), has to be the same exact layout for all platforms, just changing fonts , icons, colors, backgrounds, animations and not the structure/dispositions will be enough i bet.

**Comment by 45kb** [comment]
Everything almost ready to ship on windows.

Just stucked struggling with https://github.com/720kb/ndm/blob/master/lib/js/npm/npm-api.js#L182 which doesn't work for windows posix ofc :/

**Comment by 45kb** [comment]
@wouldgo solved it probably, moving on, stay tuned!

**Comment by 45kb** [comment]
https://github.com/720kb/ndm/issues/100 this seems to be the last obstacle.

**Comment by 45kb** [comment]
seems fixed now, if anybody can try it and give a feedback, it's just to run `npm run win` on windows (obviously) 👍

**Comment by ahallicks** [comment]
Just given this a test on Windows 10 and it seems fine for me 👍

**Comment by 45kb** [comment]
last one then gets released https://github.com/720kb/ndm/issues/105

**Comment by 45kb** [comment]
Within the next days we'll be releasing ndm **v.1** 

Finally, Windows support is done thanks to @wouldgo so the `.exe` will be shipped too.

If you'd like to try it before the time (few days really) just: `npm run win`

Any feedback is welcome, always! :D

**Comment by 45kb** [comment]
shipped! Give it a try!

Download for Windows: https://720kb.github.io/ndm/#win

@ahallicks let know if you try it ;) thanks for all your help on this.
