### ISSUE TITLE
Linux release

### ISSUE THREAD

**Issue by 45kb** [720kb/ndm#53]
later
meantime: https://github.com/720kb/ndm#b-build-the-application

**Comment by PaulBGD** [comment]
Not too bad actually
![Image](https://i.imgur.com/n6fINzO.png)

I think moving the icons from the top bar -> the menu bar would be enough to make it fit in.

**Comment by 45kb** [comment]
@PaulBGD thanks for your feedback.
 Actually it is not so difficult to port it to Linux, same for Win, even css is very easy to adapt.

We have to focus on some features and bugs that happen, before to be able to say it works, so multiple OSs will be confusing. The npm API is quite (i'd say totally) cross-platform, and the app IS the npm API itself.

Then steps will be simple:

- adapt css to linux
- adapt gulp tasks for all the OSs and releases. (i.e: switching css files before to build , or the os menu template for example , etc ..)

In the meantime a proposal of a CSS UI for Linux would be really appreciated, the layout will not change, has to be same exact layout for all platforms, just changing fonts , icons, colors and backgrounds will be enough i bet.

**Comment by PaulBGD** [comment]
I'd be willing to PR most of that, if that's okay.

**Comment by 45kb** [comment]
@PaulBGD if you're going to PR i'll be much glad to review then and possibly merge it. 

The only thing i ask you is to please follow  the guidelines 👍  https://github.com/720kb/ndm/blob/master/CONTRIBUTING.md

**Comment by 45kb** [comment]
Something is moving on 👍 

![Ubuntu](http://i.imgur.com/p7W37u0.png)

If you want to pre-run the Linux app before the release: `npm run linux` 
_the GUI may be broken because it's still work in progress_

cc @PaulBGD

**Comment by 45kb** [comment]
here are the linux executables https://720kb.github.io/ndm#linux

thanks anyway @PaulBGD and if you want to contribute there is still a lot more to do 👍

**Comment by PaulBGD** [comment]
Yeah I will if I can find the time in 2017.
