### ISSUE TITLE
Adding a project doesn't open the project

### ISSUE THREAD

**Issue by lee-dohm** [720kb/ndm#68]
* OS: macOS
* OS version: v10.12.1
* Ndm version: v0.0.3-beta
* Node version: various
* Npm version: v3.9.3
* Npm permissions (fixed, not-fixed)(see https://docs.npmjs.com/getting-started/fixing-npm-permissions): not fixed
* Node installed via (brew, n, nvm, pkg, other ...): nodenv and brew
* How to replicate the bug/issue, if you know:

1. Install ndm
1. Launch ndm
1. Click "Add Projects" button in the middle of the screen
1. Navigate to an npm project folder and click the "Open" button

**Expected:** Project to open as well as be added to the sidebar
**Actual:** Project is added to the sidebar but not opened

I also didn't notice that the first two projects I tried to open had appeared in the sidebar until I tried opening the third.

**Comment by 45kb** [comment]
@lee-dohm as the app was before the time of the releases, when opening a new project was resulting in automatically launch the pkgs list for the same project. 

Commits ago we switched from the **as-project-is-added-listing** to  the **as-user-click-on-a-project-listing**. This just due the fact that: 
if you add a new project but you want immediately list for another you'll have to wait the first project to finish listing, and (you know) npm is not so performant even on list/outdated 😐 

So your thoughts about this would be much appreciated 👍

**Comment by lee-dohm** [comment]
Personally, I think the common case is that when I add a project, I want it to open. If I add three projects simultaneously, not opening any of them is probably reasonable.

**Comment by 45kb** [comment]
appreciated a lot @lee-dohm thanks, seriously. We'll up on this sooner !

**Comment by 45kb** [comment]
https://github.com/720kb/ndm/issues/47
