### ISSUE TITLE
Installing undefined

### ISSUE THREAD

**Issue by lee-dohm** [720kb/ndm#69]
* OS: macOS
* OS version: v10.12.1
* Ndm version: v0.0.3-beta
* Node version: various
* Npm version: v3.9.3
* Npm permissions (fixed, not-fixed)(see https://docs.npmjs.com/getting-started/fixing-npm-permissions): not-fixed
* Node installed via (brew, n, nvm, pkg, other ...): nodenv and brew
* How to replicate the bug/issue, if you know:

1. Launch ndm
1. Click Globals in the sidebar
1. Click "Install Package" button
1. Click the OK button on the mini input panel

**Expected:** OK button to be disabled and nothing to happen
**Actual:** Error dialog (see below)

<img width="532" alt="screen shot 2016-12-12 at 11 30 56 pm" src="https://cloud.githubusercontent.com/assets/1038121/21131411/6787b9cc-c0c3-11e6-8566-6bdf95e1e50b.png">

**Comment by 45kb** [comment]
@lee-dohm oh this is unacceptable, my only bad, i had this in mind and did not opened an issue 😐 
Thanks a lot really.

**Comment by 45kb** [comment]
https://github.com/720kb/ndm/commit/49d06847c958aa1a7721a452d6b33635c8fb1e8c 👍
