### ISSUE TITLE
Install release with no version specified installs latest

### ISSUE THREAD

**Issue by lee-dohm** [720kb/ndm#70]
* OS: macOS
* OS version: v10.12.1 
* Ndm version: v0.0.3-beta
* Node version: various
* Npm version: v3.9.3
* Npm permissions (fixed, not-fixed)(see https://docs.npmjs.com/getting-started/fixing-npm-permissions): not-fixed (well, I didn't do anything to fix them)
* Node installed via (brew, n, nvm, pkg, other ...): nodenv and brew
* How to replicate the bug/issue, if you know:

1. Launch ndm
1. Click "Globals" in the sidebar
1. Highlight `npm` in the list of globals
1. Click "Install Release" button
1. Click OK button without entering a version to install

**Expected:** Button to be disabled and nothing to happen
**Actual:** Latest version is installed

**Comment by 45kb** [comment]
@lee-dohm ouch, thanks for the report, clearly didn't noticed this before, will fix it asap
