### ISSUE TITLE
Able to uninstall npm from globals

### ISSUE THREAD

**Issue by lee-dohm** [720kb/ndm#71]
* OS: macOS
* OS version: v10.12.1
* Ndm version: v0.0.3-beta
* Node version: various
* Npm version: v3.9.3
* Npm permissions (fixed, not-fixed)(see https://docs.npmjs.com/getting-started/fixing-npm-permissions): not-fixed (I didn't do anything to fix them)
* Node installed via (brew, n, nvm, pkg, other ...): nodenv and brew
* How to replicate the bug/issue, if you know:

1. Launch ndm
1. Click "Globals" in the sidebar
1. Highlight `npm` in the list of globals
1. Click "Uninstall"

**Expected:** Uninstall to be disabled and nothing to happen
**Actual:** npm is uninstalled thereby breaking the installation of Node

This destructive action shouldn't be possible without at least a confirmation.

**Comment by 45kb** [comment]
@lee-dohm thanks :), yes, would you suggest to prompt the user for a confirmation or to hide/disable actions for the global npm package? 

Actually, what i am thinking is that, having global npm installed for an npm manager is quite a mandatory condition to use the app itself, what do you think? 

Maybe global npm should be shown but "disabled" or hidden at all ...!?

**Comment by lee-dohm** [comment]
Personally, I think that npm is generally updated only when Node is updated. If that is the case, then I would recommend showing npm in the list but disabled. If npm is, under some circumstances, updated separately from Node, I would recommend allowing it to be selected but with a confirmation.

**Comment by 45kb** [comment]
By now, as you select npm (in globals) and try to uninstall it, you have to confirm to continue 👍

**Comment by 45kb** [comment]
definitely changed direction: the npm package is disabled in globals by now. https://github.com/720kb/ndm/commit/37d4b0fc84faf737686625352aea68fdbc8a553a
