### ISSUE TITLE
"Contribute" and "Support" labels in status bar are confusing

### ISSUE THREAD

**Issue by lee-dohm** [720kb/ndm#72]
* OS: macOS
* OS version: v10.12.1 
* Ndm version: v0.0.3-beta
* Node version: various
* Npm version: v3.9.3
* Npm permissions (fixed, not-fixed)(see https://docs.npmjs.com/getting-started/fixing-npm-permissions): not-fixed (I didn't do anything to them)
* Node installed via (brew, n, nvm, pkg, other ...): nodenv and brew
* How to replicate the bug/issue, if you know:

1. Launch ndm
1. Look at the status bar

**Expected:** Not to see two labels asking for money
**Actual:** Two labels asking for money

You could probably do away with both and just have a [repo octicon](https://octicons.github.com/icon/repo/) there or something :grinning:

**Comment by 45kb** [comment]
@lee-dohm  Lovely icons you're right... and yes they are confusing so the "footer" is going to be emptied with the next commits, so that we could use it for more, like for example show the npm registry status or more... 🎱

**Comment by 45kb** [comment]
https://github.com/720kb/ndm/commit/c87d34154cb712be0283dc70fb34f345b2dee5ee 🎯
