### ISSUE TITLE
Install in project context menu and "Install Package" button mean different things

### ISSUE THREAD

**Issue by lee-dohm** [720kb/ndm#73]
* OS: macOS
* OS version: v10.12.1 
* Ndm version: v0.0.3-beta
* Node version: various
* Npm version: v3.9.3
* Npm permissions (fixed, not-fixed)(see https://docs.npmjs.com/getting-started/fixing-npm-permissions): not-fixed (I didn't do anything to them)
* Node installed via (brew, n, nvm, pkg, other ...): nodenv and brew
* How to replicate the bug/issue, if you know:

1. Launch ndm
1. Add a project
1. Right-click the project in the sidebar
1. Click "Install"
1. Watch ndm run `npm install` in the project's directory
1. Click "Install Package" button with project still selected in sidebar

**Expected:** The two functions to do roughly the same thing
**Actual:** One runs `npm install` the other runs `npm install --save [some package]`

The distinction between the two should be clearer.

**Comment by 45kb** [comment]
@lee-dohm this is an ouch v2 :D , right.... maybe showing "Init" but `init` has a own scope in npm, maybe showing "npm install" !? 🎱  Before the time all the prune, dedupe, install etc where prefix with "npm" but i don't know if it's more clear the difference prefixing them... i'd like to know what you think you would do for this if possible.

**Comment by lee-dohm** [comment]
I think the problem is that you're sticking too close to the command-line interface. What if "Install" was "Install All" and "Install Package" was "Add Package"? At least then, it would be obvious that the two operations were different.

**Comment by 45kb** [comment]
@lee-dohm actually, agree... thinking about some tries in that way so.
thanks :)
